name: chat_app_nnt
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  the_validator: ^2.0.0
  provider: ^6.0.1

  #make color
  flutter_svg: ^0.23.0+1
  simple_gradient_text: ^1.2.2
  new_gradient_app_bar: ^0.2.0
  bottom_picker: ^1.0.5
  date_format: ^2.0.4
  flutter_switch: ^0.3.2
  auto_size_text: ^3.0.0
  dartx: ^1.0.0

  #icon
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1

  #firebase
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.0

  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #splash screen
  flutter_native_splash: ^1.3.1

flutter_native_splash:
  color: "#F7EDE1"
  color_dark: "#1d1d1d"
  android: true
  ios: true
  image: "assets/images/logo_splash_150.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Arial Rounded MT Bold
      fonts:
        - asset: assets/fonts/Arial-Rounded-MT-Bold.ttf

    - family: Harabara Mais Demo
      fonts:
        - asset: assets/fonts/Harabara-Mais-Demo.ttf

    - family: MADE Waffle Soft
      fonts:
        - asset: assets/fonts/Made-Waffle-Soft.ttf

    - family: Hiragino Sans
      fonts:
        - asset: assets/fonts/Hiragino-Sans.ttf

    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
